### ISSUE TITLE
Heroku deployment - Is it necessary to globally install the node dependency ?

### ISSUE THREAD

**Issue by jay-meister** [coletiv/puppeteer-pdf#8]
I'm slightly confused with Heroku deployment. 

I don't want to rely on a globally installed dependency if possible. Locally I seem to be able to run this without issue with the following config:

in my config.exs:
`config :puppeteer_pdf, exec_path: File.cwd!() <> "/assets/node_modules/.bin/puppeteer-pdf"`

However when running in Heroku, I get the following error:

```
2019-03-06T11:48:01.393897+00:00 app[web.1]: /app/assets/node_modules/puppeteer-pdf/puppeteer-pdf.js:74
2019-03-06T11:48:01.393907+00:00 app[web.1]: (async () => {
2019-03-06T11:48:01.393908+00:00 app[web.1]: ^
2019-03-06T11:48:01.393910+00:00 app[web.1]: SyntaxError: Unexpected token (
2019-03-06T11:48:01.393911+00:00 app[web.1]: at Object.exports.runInThisContext (vm.js:76:16)
2019-03-06T11:48:01.393912+00:00 app[web.1]: at Module._compile (module.js:542:28)
2019-03-06T11:48:01.393913+00:00 app[web.1]: at Object.Module._extensions..js (module.js:579:10)
2019-03-06T11:48:01.393914+00:00 app[web.1]: at Module.load (module.js:487:32)
2019-03-06T11:48:01.393915+00:00 app[web.1]: at tryModuleLoad (module.js:446:12)
2019-03-06T11:48:01.393916+00:00 app[web.1]: at Function.Module._load (module.js:438:3)
2019-03-06T11:48:01.393917+00:00 app[web.1]: at Module.runMain (module.js:604:10)
2019-03-06T11:48:01.393918+00:00 app[web.1]: at run (bootstrap_node.js:394:7)
2019-03-06T11:48:01.393919+00:00 app[web.1]: at startup (bootstrap_node.js:149:9)
2019-03-06T11:48:01.393920+00:00 app[web.1]: at bootstrap_node.js:509:3
```

Although the PDF does get generated.

Any idea what that error is about? Is it ok to run this module without a globally installed `puppeteer-pdf` Node module?

**Comment by speeddragon** [comment]
I'm not an experience user in Node, but you just need the binary to work and have all dependencies associated with it. 

Maybe your issue is related to [this](https://stackoverflow.com/a/37815872/641611) ? Check if your node version is above 7.6

**Comment by jay-meister** [comment]
Upgraded version and still running into issues. Possibly need a heroku buildpack to run this on Heroku:

https://github.com/jontewks/puppeteer-heroku-buildpack


Taken from issue on puppeteer:

https://github.com/GoogleChrome/puppeteer/issues/758

I'll continue looking into this.

**Comment by jay-meister** [comment]
This did it:

https://github.com/jontewks/puppeteer-heroku-buildpack
